spring:
  profiles: local
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      authentication-database: admin
      username: mongoadmin
      password: admin
      database: school-teacher-db
      port: 27017
      host: localhost

server:
  port: 2500

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

